FROM centos:7
WORKDIR /root
RUN yum update -y && yum install git java-1.8.0-openjdk telnet net-utils gcc bind-utils centos-release-scl -y && yum install rh-python35 -y && scl enable rh-python35 bash

