---
kind: Service
apiVersion: v1
metadata:
  name: default-subdomain
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: spark-worker-spark-cluster-01
