kind: Service
apiVersion: v1
metadata:
  name: spark-job-service
  namespace: bsavoy
spec:
  type: NodePort
  selector:
    app: spark
  ports:
  - protocol: TCP
    port: 7077
---
kind: Service
apiVersion: v1
metadata:
  name: spark-ui-service
  namespace: bsavoy
spec:
  type: NodePort
  selector:
    app: spark
  ports:
  - protocol: TCP
    port: 8080
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-deployment
  namespace: bsavoy
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark-og
        image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER}
        resources:
          limits:
            cpu: "1000m"
            memory: "2048Mi"
          requests:
            cpu: "500m"
            memory: "1024Mi"
