apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job-${JOB_NAME}-${BUILD_NUMBER}
  namespace: ${K8S_NAMESPACE}
spec:
  template:
    spec:
      containers:
      - name: spark-submitter-${JOB_NAME}-${BUILD_NUMBER}
        image: ${SUBMIT_POD_IMAGE}
        env:
        - name: SPARK_SUBMIT_ARGS
          value: "${SUBMIT_PARAMS}"
      restartPolicy: Never
  backoffLimit: 0
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ${K8S_NAMESPACE}
  name: spark-pod-mgr
rules:
- apiGroups: ["","batch"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list", "delete", "create", "edit"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-admin-binding
  namespace: ${K8S_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-pod-mgr
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${K8S_NAMESPACE}
