kind: Service
apiVersion: v1
metadata:
  name: ${SPARK_MASTER_URL}-spark-master
  namespace: ${K8S_NAMESPACE}
spec:
  type: NodePort
  selector:
    app: spark-master-${SPARK_MASTER_URL}
  ports:
  - protocol: TCP
    port: 7077
---
kind: Service
apiVersion: v1
metadata:
  name: ${SPARK_MASTER_URL}-spark-ui
  namespace: ${K8S_NAMESPACE}
spec:
  type: NodePort
  selector:
    app: spark-master-${SPARK_MASTER_URL}
  ports:
  - protocol: TCP
    port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: ${SPARK_MASTER_URL}-spark-app-ui
  namespace: ${K8S_NAMESPACE}
spec:
  type: NodePort
  selector:
    app: spark-worker-${SPARK_MASTER_URL}
  ports:
  - protocol: TCP
    port: 4040
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-master-${SPARK_MASTER_URL}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: spark-master-${SPARK_MASTER_URL}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master-${SPARK_MASTER_URL}
  template:
    metadata:
      labels:
        app: spark-master-${SPARK_MASTER_URL}
    spec:
      containers:
      - name: spark-master-${SPARK_MASTER_URL}
        image: ${DOCKER_REGISTRY}/${MASTER_IMAGE_NAME}:${BUILD_NUMBER}
        env:
        - name: PYSPARK_PYTHON
          value: "python3"
        - name: PYSPARK_DRIVER_PYTHON
          value: "python3"
        resources:
          limits:
            cpu: "1000m"
            memory: "2048Mi"
          requests:
            cpu: "500m"
            memory: "1024Mi"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ${SPARK_MASTER_URL}-spark-worker
  namespace: ${K8S_NAMESPACE}
  labels:
    app: spark-worker-${SPARK_MASTER_URL}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: spark-worker-${SPARK_MASTER_URL}
  template:
    metadata:
      labels:
        app: spark-worker-${SPARK_MASTER_URL}
    spec:
      containers:
      - name: spark-worker-${SPARK_MASTER_URL}
        image: ${DOCKER_REGISTRY}/${WORKER_IMAGE_NAME}:${BUILD_NUMBER}
        env:
        - name: SPARK_MASTER_URL
          value: "${SPARK_MASTER_URL}-spark-master:7077"
        - name: PYSPARK_PYTHON
          value: "python3"
        - name: PYSPARK_DRIVER_PYTHON
          value: "python3"
        - name: SPARK_WORKER_MEMORY
          value: "${WORKER_SHAPE_MEM}"
        - name: SPARK_WORKER_CORES
          value: "${WORKER_SHAPE_CPU}"
        resources:
          limits:
            cpu: "${WORKER_SHAPE_CPU}000m"
            memory: "${WORKER_SHAPE_MEM}Mi"
