---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-service-${NB_ID}
  namespace: bsavoy
spec:
  type: NodePort
  selector:
    app: jupyter-${NB_ID}
  ports:
  - protocol: TCP
    port: 8888
    nodePort: 30909
    targetPort: 8888
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jupyter-deployment-${NB_ID}
  namespace: bsavoy
  labels:
    app: jupyter-${NB_ID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-${NB_ID}
  template:
    metadata:
      labels:
        app: jupyter-${NB_ID}
    spec:
      containers:
      - name: jupyter-${NB_ID}
        image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER}
        resources:
          limits:
            cpu: "1000m"
            memory: "2048Mi"
          requests:
            cpu: "500m"
            memory: "1024Mi"
