---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-service
  namespace: bsavoy
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 30800
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jupyter-deployment
  namespace: bsavoy
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter-og
        image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER}
        resources:
          limits:
            cpu: "1000m"
            memory: "2048Mi"
          requests:
            cpu: "500m"
            memory: "1024Mi"
