kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
  namespace: bsavoy
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
    
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jenkins-deployment
  namespace: bsavoy
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-og
        image: instance-1.us-east1-b.c.sandbox-224519.internal:8080/jenkins:201812281
        env:
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false -DXmx=4096M -DXms=2048M"
        - name: DOCKER_CONFIG
          value: "/home/.docker"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: kubeconfigsecret
          mountPath: /home/.kube
        - name: dockerconfigsecret
          mountPath: /home/.docker
          readOnly: true
        resources:
          limits:
            cpu: "2000m"
            memory: "4096Mi"
          requests:
            cpu: "2000m"
            memory: "2048Mi"
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home-pvc
      - name: docker-sock
        persistentVolumeClaim:
          claimName: jenkins-dockersock-pvc
      - name: kubeconfigsecret
        secret:
          secretName: jenkins-k8s-kube-config
      - name: dockerconfigsecret
        secret:
          secretName: jenkins-docker-config
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-home-pv
  namespace: bsavoy
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: bsavoy
    name: jenkins-home-pvc
  hostPath:
   path: /k8s-pvs/jenkins_home
   type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home-pvc
  namespace: bsavoy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-dockersock-pv
  namespace: bsavoy
spec:
  capacity: 
    storage: 1Gi
  accessModes: 
    - ReadWriteMany
  claimRef:
    namespace: bsavoy
    name: jenkins-dockersock-pvc
  hostPath:
   path: /var/run/docker.sock
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-dockersock-pvc
  namespace: bsavoy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
